import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mistral Docs Example (Next.js)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          display: "flex",
          flexDirection: "row",
          margin: 0,
          padding: 0,
          position: "absolute",
          inset: 0,
        }}
      >
        <div
          style={{
            flex: "0 1 400px",
            borderRight: "1px solid var(--speakeasy-border-color)",
            marginRight: "1rem",
            padding: "1rem",
            overflow: "auto",
          }}
        >
          <Sidebar />
        </div>
        <div style={{ flex: "1 1 100%", overflow: "auto" }}>{children}</div>
      </body>
    </html>
  );
}
