openapi: 3.0.0
info:
  title: Petstore API
  description: A simple API for managing a pet store
  version: 1.0.0
servers:
  - url: https://petstore.swagger.io/v2
paths:
  /pets:
    get:
      summary: Get all pets
      description: Returns a list of all pets in the store
      operationId: getPets
      responses:
        "200":
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: "#/components/schemas/Dog"
                    - $ref: "#/components/schemas/Cat"
    post:
      summary: Add a new pet
      operationId: addPet
      tags:
        - Pet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/Dog"
                - $ref: "#/components/schemas/Cat"
      responses:
        "201":
          description: Pet added successfully
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Dog"
                  - $ref: "#/components/schemas/Cat"
  /pets/{petId}:
    get:
      summary: Get a pet by ID
      operationId: getPetById
      tags:
        - Pet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Pet details
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Dog"
                  - $ref: "#/components/schemas/Cat"
        "404":
          description: Pet not found
components:
  schemas:
    Dog:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          description: The name of the dog
          example: Rambo
        details:
          type: object
          properties:
            breed:
              type: string
              enum:
                - Terrier
                - Labrador
                - German Shepherd
              description: The breed of the dog
              example: Terrier
            age:
              type: integer
              description: The age of the dog
              example: 13
    Cat:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          format: uuid
          description: The name of the cat
          example: Whiskers
        details:
          type: object
          properties:
            breed:
              type: string
              enum:
                - Tabby
                - Siamese
                - Persian
              description: The breed of the cat
              example: Tabby
            age:
              type: integer
              description: The age of the cat
              example: 7
