name: E2E Tests

on:
  workflow_call:
    inputs:
      use-artifacts:
        description: 'Whether to use artifacts from the packages workflow'
        required: false
        type: boolean
        default: true
  workflow_dispatch:

jobs:
  integration-tests:
    name: Playwright Integration Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Needed to copy the WASM file during build
          lfs: true
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Download build artifacts
        id: download-artifacts
        if: inputs.use-artifacts
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: package-build-artifacts
      - name: Restore build artifacts
        if: steps.download-artifacts.outcome == 'success'
        run: tar -xzf build-artifacts.tar.gz
      - name: Build packages (if artifacts not available)
        if: ${{ !inputs.use-artifacts || steps.download-artifacts.outcome != 'success' }}
        run: make build-packages
      # We have to run npm install again to link the newly built compiler binary
      - name: Link workspace binaries
        run: npm install --workspaces
      - name: Build examples
        run: |
          npm run build --workspace examples/docusaurus --ignore-scripts &
          npm run build --workspace examples/nextra --ignore-scripts &
          wait
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: tests/integration
      - name: Run Playwright tests
        run: make test-integration
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/integration/playwright-report/
          retention-days: 30
