name: Examples

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, new-try-it-now]
  merge_group:

jobs:
  build-and-test:
    name: Example Build Verification
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Needed to copy the WASM file during Docs MD build
          lfs: true
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm ci
      - name: Build Packages
        run: make build-packages
      # We have to run npm install again to link the newly built compiler binary
      - name: Link workspace binaries
        run: npm install --workspaces
      - name: Verify example builds
        run: make verify-api-docs
