name: Packages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, new-try-it-now]
  merge_group:

jobs:
  build-and-test:
    name: Packages Build and Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Needed to copy the WASM file during build
          lfs: true
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm ci
      - name: Build packages
        run: make build-packages
      - name: Type check
        run: make type-check-packages
      - name: Lint
        run: make lint-packages
      - name: Check formatting
        run: make check-formatting-packages
      - name: Verify package versions
        run: make verify-package-versions
