name: Petstore Docusaurus Example

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  build-and-test:
    name: Petstore Docusaurus Example Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm ci
      - name: Build Docs MD
        working-directory: ./packages/docs-md
        run: npm run build
      - name: Build Docusaurus
        working-directory: ./examples/docusaurus/petstore
        run: npm run build
